version: '3'

networks:
  inception42:

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/verdant/home/mwilsch/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/verdant/home/mwilsch/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    networks:
      - inception42
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    networks:
      - inception42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/
    env_file:
      - .env
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    networks:
      - inception42
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/
    restart: always

